### ISSUE TITLE
Upgrade dependency on crate `platforms`

### ISSUE THREAD

**Issue by Forsworns** [rust-psutil/rust-psutil#95]
Hi, I use the git actions for CI. And from last Sunday, it failed on build and reported that the dependency `platforms` is deprecated

```
error: failed to select a version for the requirement `platforms = "^0.2.1"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.3, ...
location searched: crates.io index
required by package `psutil v3.2.1`
    ... which satisfies dependency `psutil = "^3.2.1"`  
```

And on [crates.io](https://crates.io/crates/platforms/versions), version 0.2.1 has been yanked.

Do you have any roadmaps on dependency upgrading?

**Comment by iagox86** [comment]
+1 - I'm unable to use this crate due to this dependency:

```
$ cat Cargo.toml 
[package]
name = "project"
version = "0.1.0"
edition = "2018"

[dependencies]
psutil = "~3.2.0"
$ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `platforms = "^0.2.1"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.3, ...
location searched: crates.io index
required by package `psutil v3.2.0`
    ... which satisfies dependency `psutil = "~3.2.0"` of package `project v0.1.0 (/home/ron/project)`
```

**Comment by gabrik** [comment]
Same here, build always failing on this crate

**Comment by iagox86** [comment]
As a work around, `sysinfo` covered what I needed (though wasn't quite as nice to use): https://docs.rs/sysinfo/latest/sysinfo/

**Comment by AaronO** [comment]
Not a fix but if you don't actually depend on features provided through `platforms` (`psutil::host`), you can workaround it.

(features and their dependencies)
```toml
[features]
default = ["cpu", "disk", "host", "memory", "network", "process", "sensors"]
serde = ["renamed_serde", "platforms/serde"]

# Modules
cpu = ["mach", "num_cpus"]
disk = ["derive_more", "unescape"]
host = ["platforms"]
memory = ["mach"]
network = ["derive_more"]
process = ["darwin-libproc", "mach", "memory"]
sensors = ["glob"]
```

By disabling default features and selecting only the ones you need, e.g:
```toml
psutil = { version = "3.2.1", default-features = false, features = ["memory", "process"] }
```
